### ISSUE TITLE
Only two banks showing on dropdown list

### ISSUE THREAD

**Issue by Karma-234** [wilburt/flutter_paystack#157] opened 2023-04-04 05:25 UTC
In bank checkout, the dropdown only shows two banks. GTb and zenith

**Comment by Leekogram** [comment] 2023-04-15 18:37
Please can you resolve this issue, because I built an App for my company in which i used this plugin and we are about to launch and this is an issue someone raised, can we atleast know what the problem is why is it showing only two banks, mine is Gt bank and Kuda bank Only. And if there is any workaround Thanks.

**Comment by Andrew-Paystack** [comment] 2023-04-17 08:05
Hey @Karma-234 @Leekogram , 

Thanks for reaching out!

This isn't an issue with the library actually. The library is working based on responses from the API. 

We're showing the banks that we currently have on the platform. When more banks become available we'll definitely implement them

You can confirm this by visiting [paystack.com/demo](https://paystack.com/demo/checkout) and try a transaction. You'll see the library shows the banks too. 

Let me know if you have any further issues.

**Comment by Leekogram** [comment] 2023-04-17 09:47
> Hey @Karma-234 @Leekogram ,
> 
> Thanks for reaching out!
> 
> This isn't an issue with the library actually. The library is working based on responses from the API.
> 
> We're showing the banks that we currently have on the platform. When more banks become available we'll definitely implement them
> 
> You can confirm this by visiting [paystack.com/demo](https://paystack.com/demo/checkout) and try a transaction. You'll see the library shows the banks too.
> 
> Let me know if you have any further issues.

Alright, Thanks

**Comment by Hafsa-Awan** [comment] 2023-05-03 14:16
hi @Andrew-Paystack  i have issue when i apply the bank method it shows the exception "pass an accessCode". i don't know why but the accessCode is only required when we initiate transaction from the backend(what I understood from flutter_paystack plugin docs)

**Comment by Leekogram** [comment] 2023-05-03 16:03
> hi @Andrew-Paystack i have issue when i apply the bank method it shows the exception "pass an accessCode". i don't know why but the accessCode is only required when we initiate transaction from the backend(what I understood from flutter_paystack plugin docs)
<img width="1428" alt="Screenshot 2023-05-03 at 4 54 05 PM" src="https://user-images.githubusercontent.com/33817077/235973318-8dd1778d-fd57-426c-a1ec-951483156db5.png">

**Comment by wilburx9** [comment] 2023-05-04 01:13
@Hafsa-Awan  access code is required for bank payments.

Closing this issue since the original problem has been addressed.

**Closed as completed by wilburx9** 2023-05-04 01:13 UTC
