### ISSUE TITLE
the cardholder was not authorized

### ISSUE THREAD

**Issue by quiet-programmer** [wilburt/flutter_paystack#74] opened 2020-11-01 21:02 UTC
the cardholder was not authorized. this is used in 3-d secure authentication. I was not allowed to process a transaction when the plugin popped up another dialog telling me to wait for verification, I was expecting it to show me what to do, but nothing.

Any help will be useful please

**Comment by wilburt** [comment] 2020-11-01 21:04
Did this happen in staging? If yes, what card details did you use?

**Comment by quiet-programmer** [comment] 2020-11-01 21:05
For all I know I have read through the Paystack docs for that, saw that it's to verify if the transaction is coming from the owner of the card. I think ave seen this a lot which paying using a website it redirects to Visa or Master card verification page

i think that was what wanted to happen but did not.

**Comment by quiet-programmer** [comment] 2020-11-01 21:06
> Did this happen in staging? If yes, what card details did you use?

card details?

**Comment by quiet-programmer** [comment] 2020-11-01 21:07
I used the card number, expiring date and cvv number

**Comment by wilburt** [comment] 2020-11-01 21:08
Yes, if this happened in staging, it means you might have used one of the [Paystack test cards](https://paystack.com/docs/payments/test-payments/).

**Comment by wilburt** [comment] 2020-11-01 21:08
Any way I can reproduce this?

**Comment by quiet-programmer** [comment] 2020-11-01 21:10
> Yes, if this happened in staging, it means you might have used one of the [Paystack test cards](https://paystack.com/docs/payments/test-payments/).

Nop..... I used my bank card for this. and I was threw that error

**Comment by quiet-programmer** [comment] 2020-11-01 21:11
thanks for the response bro... appreciated

**Comment by wilburt** [comment] 2020-11-01 21:12
The dialog in question does it have any private information? If no, can you send a screenshot?

**Comment by quiet-programmer** [comment] 2020-11-01 21:31
![20201101_223059.png](https://user-images.githubusercontent.com/44076215/97815933-fe775080-1c91-11eb-9996-d9275bebd1e9.png)

**Comment by quiet-programmer** [comment] 2020-11-01 21:33
Or you asking for the other dialog... wait let me run the process again and screenshot it

**Comment by quiet-programmer** [comment] 2020-11-01 21:41
![20201101_224040.png](https://user-images.githubusercontent.com/44076215/97816137-56628700-1c93-11eb-90aa-55589886e55e.png)

**Comment by quiet-programmer** [comment] 2020-11-01 21:42
After this.... it shows me "the cardholder was not authorized"

**Comment by wilburt** [comment] 2020-11-01 21:45
Please, can you try a payment in staging and let me know if this also happens? Please use the [ test card](https://paystack.com/docs/payments/test-payments/) titled "Bank Auth Simulation".

**Comment by quiet-programmer** [comment] 2020-11-01 22:16
Okay it did that but... the transaction was successful... I used my Visa card on a live account of PayStack but it will just say processing and fail the transaction...

but with this test card it just did processing and display a msg saying "close tap to continue" after closing tab, transaction was made successful

**Comment by TMoreMaker** [comment] 2021-02-18 18:39
I'm having the same problem. On the dashboard on paystack, the transactions are marked as ongoing

**Comment by quiet-programmer** [comment] 2021-02-18 21:33
> I'm having the same problem. On the dashboard on paystack, the transactions are marked as ongoing
> EDIT:This seems to be a problem only when other authentification methods are required

so you got your way around it?

**Comment by TMoreMaker** [comment] 2021-02-23 11:15
@quiet-programmer So did you get it to work or is it a limitation of the plugin?

**Comment by quiet-programmer** [comment] 2021-02-23 11:27
Later worked perfectly fine... when I removed the version name number of the plugin in pubspec.yaml 

From-> flutter_paystack: version number
To -> flutter_paystack:

Clean flutter build and rerun build 

That worked for me...

**Comment by wilburt** [comment] 2021-03-14 03:10
I will be closing this issue since it appears to have been resolved.

**Closed by wilburt** 2021-03-14 03:10 UTC
Labels: help wanted
