### ISSUE TITLE
Amount Error

### ISSUE THREAD

**Issue by nixcode1** [wilburt/flutter_paystack#78] opened 2020-12-08 01:47 UTC
Hello. The plugin works fine when I added amount and email to the rest of the options.

However, I was reading the docs today and saw that if I was using an acesscode from my backend server, I didn't need to input amount or email, just acesscode.

When i tried this, I got a "-1 is not a valid amount. only positive non-zero values are allowed." error.

Would appreciate some explanation for why the code failed or did I misinterpret the docs?

**Comment by wilburt** [comment] 2020-12-08 06:15
No, you didn't misinterpret the docs. Please, verify from the backend dev if they are passing a valid amount when generating the access code.

**Comment by nixcode1** [comment] 2020-12-08 10:52
I will do so and get back to you.

Thank you for such a great plugin

**Comment by nixcode1** [comment] 2020-12-10 17:38
So I checked with the backend engineer and he said the payment is initialize with amount and email, the web url to checkout.paystack confirms this

**Comment by wilburt** [comment] 2021-02-15 13:40
@nixcode1  does this issue still persist?

**Comment by nixcode1** [comment] 2021-02-17 18:16
Should I update the package before checking? It existed the last time checked

**Comment by wilburt** [comment] 2021-03-14 03:15
If an access code is used, Paystack uses the amount passed during the generation of the access code. Therefore, II will be closing this issue since it's not reproducible and it appears to be a backend issue.

**Closed by wilburt** 2021-03-14 03:15 UTC
Labels: question
